name: Python Application CI/CD

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: pytest test.py

  build:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build application
        run: python app.py
          

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to staging
        run: python app.py
     
      - name: checking out code on runner
        uses: actions/checkout@v4

      - name: login and update EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with: 
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            port: 22
            script: |
              whoami
              ls
              pwd

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to production
        run: python app.py
