name: Python Application CI/CD

on:
  push:
    branches:
      - staging
      - main


jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
  run-tests:
    name: Test
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 flaskr --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 flaskr --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: login and update EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo apt-get update -y
            mkdir FlaskApp
                
      - name: copy file via git repo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: ./
          target: /home/ubuntu/FlaskApp/
                
      - name: SSH commands using password Deploy to Staging Environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo apt install python3-pip -y
            python3 -m pip install --upgrade pip          
            cd /home/ubuntu/FlaskApp/
            pip install -r requirements.txt
            sudo kill -9 $(sudo lsof -t -i:3000)
            python3 app.py
            
  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: login and update EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with: 
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            port: ${{ secrets.EC2_PORT }}
            script: |                
                sudo apt-get update -y                
                mkdir FlaskApp
                
      - name: copy file via git repo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: ./
          target: /home/ubuntu/FlaskApp/
                
      - name: SSH commands using password Deploy to Production Environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo apt install python3-pip -y
            python3 -m pip install --upgrade pip          
            cd /home/ubuntu/FlaskApp/
            pip install -r requirements.txt
            sudo kill -9 $(sudo lsof -t -i:3000)
            python3 app.py
