name: Python Application CI/CD

on:
  push:
    branches:
      - staging
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest Flask

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Run tests
        run: | 
          pip install pytest Flask
          pytest test.py

  build:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Build application
        run: | 
          pip install pytest Flask
          nohup python app.py > output.log &         

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to staging
        run: | 
          pip install Flask
          nohup python app.py > output.log &
     


  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to production
        run: |
          pip install Flask
          nohup python app.py > output.log &
