name: Python Application CI/CD

on:
  push:
    branches:
      - staging
      - main
  release:
    types: [published]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: login and update EC2 instance
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
          architecture: 'x86'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          
          
