name: Python Application CI/CD

on:
  push:
    branches:
      - staging
      - main
  release:
    types: [published]

jobs:
 install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip3
          pip3 install -r requirements.txt
        
